name: ‚ùå Bug report
description: Report errors or unexpected behavior
labels: ‚ùå bug
body:
- type: checkboxes
  attributes:
      label: üßê Have you fully read the README and viewed similar issues?
      description: Please read the <a href="https://github.com/SpotX-CLI/SpotX-Mac/blob/main/readme.md">README</a>. Also check the open and closed <a href="https://github.com/SpotX-CLI/SpotX-Mac/issues">issue</a> because your issue may have already been fixed.
      options:
        - label: I have read the README
          required: true
        - label: I have checked older issues, open and closed
          required: true
        - label: I did a clean install of Spotify and SpotX
          required: true
- type: markdown
  attributes:
    value: "###"    
- type: input
  id: lang_spoti
  attributes:
    label: –°ountry of your account
    description: You can view your country on your account page, in paragraph <a href="https://www.spotify.com/account/">Country or region</a>.
    placeholder: "e.g. Ukraine"
  validations:
    required: true 
- type: markdown
  attributes:
    value: "###"     
- type: dropdown
  id: plan
  attributes:
    label: What is your Spotify Plan?
    description: You can view your plan on your account page, under <a href="https://www.spotify.com/account/">Your plan</a>.
    options:
      - Free
      - Premium
  validations:
    required: true
- type: markdown
  attributes:
    value: "###"        
- type: dropdown
  id: spicetify
  attributes:
    label: Do you have Spicetify installed?
    description: <a href="https://spicetify.app/">Spicetify</a> is a command line tool to customize Spotify client.
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: markdown
  attributes:
    value: "###"       
- type: textarea
  attributes:
    label: ‚Ñπ Computer information
    description: |
      - Spotify: e.g. <kbd>Spotify for macOS (Apple Silicon) 1.1.98.683.g5a3b77ad</kbd>
        - With Spotify open and in focus, in the top toolbar, click <kbd>Spotify</kbd> ‚Üí <kbd>About Spotify</kbd> ‚Üí <kbd>About Spotify</kbd>
        - Click on the `Copy version info` button to copy the Spotify version info to your clipboard.
      - macOS: e.g. <kbd>macOS Ventura 13.0</kbd> 
        - Click Apple menu (top left of screen) then select <kbd>About This Mac</kbd> to open the system information window to view macOS info.
      - Shell: e.g. <kbd>bash</kbd>
        - With Terminal open, view the top bar in the Terminal window -- it should display bash or zsh (or whatever else you've set as your shell).
    placeholder: |
        - Spotify: 
        - macOS: 
        - Shell:  
    value: |
        - Spotify: 
        - macOS: 
        - Shell: 
    render: markdown   
  validations:
    required: true    
- type: textarea
  attributes:
    label: üìù Description
    description: List steps to reproduce the error and details on what happens and what you expected to happen.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: üñµ Terminal Output
    description: Copy output from Terminal -- the SpotX command you entered and everything that followed.
  validations:
    required: true
- type: textarea
  attributes:
    label: üì∏ Screenshots
    description: Place any screenshots of the issue here if needed
  validations:
    required: false    
    
